trufont/trufont

Lib/defconQt/fontView.py
```
Traceback (most recent call last):
File "trufont/Lib/defconQt/fontView.py", line 1075, in inspector
app.inspectorWindow = InspectorWindow()
File "trufont/Lib/defconQt/fontView.py", line 221, in __init__
layerSetLayout.addWidget(LayerSetList(app.currentFont()), 0, 0)
File "trufont/Lib/defconQt/layerSetList.py", line 10, in __init__
super().__init__(parent, *args, **kwargs)
TypeError: QListWidget(QWidget parent=None): argument 1 has unexpected type 'TFont'
```
LayerSetList() instead of LayerSetList(app.currentFont()) because of https://github.com/trufont/trufont/commit/816748b6d6b14b8b9f80fc904dc2654fd3e0f7c1#diff-63b827e0c990e4937144d052e54e794cL8
=> fontView: LayerSetList() doesn’t take TFont as argument since 816748b

Lib/defconQt/__main__.py, Lib/defconQt/fontView.py, Lib/defconQt/objects/defcon.py, Lib/defconQt/util/glyphList.py
@moyogo What do you think?
This adds support of custom glyph lists in the form `A;0041` as in AGL (not AGLFN which is backwards and has an additional field). 
I was thinking, since glyph names in UFO are unboun, you could very much have ; in a glyph name.
=> meta: add custom glyphList support

Lib/defconQt/__main__.py
Avoid crashing the application in case there's not yet any config file, by passing a default value to the glyphList entry in the TruFont settings.
=> Avoid crashing the application in case there's not yet any config file

.travis.yml, INSTALL.md, requirements.txt
Having to install dependencies manually can be troublesome. Not only does it take longer, but updating packages and version locking becomes difficult.
This change adds a `requirements.txt` so that all Python packages (except for PyQt5) can be installed via `pip` with a single command.
Update the `INSTALL.md` file with new instructions that use the `requirements.txt` file. Also add a note to this file about how to use Virtualenv with the project (because of the way PyQt5 needs to be installed).
=> Add requirements.txt

Lib/defconQt/fontInfo.py, tests/defconQt/fontInfo_test.py
These two fields typically have longer text that doesn’t into a single
line and using QLineEdit makes editing them cumbersome.
=> Use QPlainTextEdit for copyright and license in font info

.gitignore, Lib/defconQt/__main__.py, Lib/defconQt/featureTextEditor.py, Lib/defconQt/fontInfo.py, Lib/defconQt/fontView.py, Lib/defconQt/glyphCollectionView.py, Lib/defconQt/glyphView.py, Lib/defconQt/groupsView.py, Lib/defconQt/metricsWindow.py, Lib/defconQt/objects/glyphDialogs.py, Lib/defconQt/scriptingWindow.py, Lib/defconQt/tools/baseButton.py, Lib/defconQt/tools/baseTool.py, Lib/defconQt/tools/knifeTool.py, Lib/defconQt/tools/penTool.py, Lib/defconQt/tools/removeOverlapButton.py, Lib/defconQt/tools/rulerTool.py, Lib/defconQt/tools/selectionTool.py, Lib/defconQt/translations.pro, Lib/defconQt/util/drawing.py, Lib/defconQt/util/glyphList.py, Lib/defconQt/util/platformSpecific.py
I'd like to get this in, but maybe without my example translation. As long as the HIG/UI has not stabilized, it is only useful for testing.
Known problems:
- Translations don't load when starting via `trufont` -- package into resource file?
- `pylupdate5` gets confused when strings contain non-ASCII characters. Either avoid or escape them (quotation marks!) or attach them afterwards (ellipsis).
Notes:
- When sizing elements like buttons and columns, don't set a fixed width based on the length of English words. I'd fix fontView.py's glyphListButton if I knew why sizeHint() makes it so wide.
=> Translation support

Lib/defconQt/glyphCollectionView.py, Lib/defconQt/metricsWindow.py
- `metricsWindow.py`: remove setupFileMenu, unused
- `glyphCollectionView.py`: move proceedWithDeletion into GlyphCollectionWidget.
=> Minor code cleanup.

README.md
I was reading the README.md and I noticed that it says
> run under virtualenv: `cd Lib && python -m defconQt`
That's a bit misleading. The command simply runs trufont in place, it doesn't mean it runs from an isolated virtual environment, as the reference to `virtualenv` seems to imply.
I think it'd be better if we recommend users, and especially developers, to install trufont and its many dependencies inside a virtual environment (a "real" one ;).
Let me know what you think.
=> [README.md] add install info on python 3, pyqt5 and virtual environment

.travis.yml
pyqt5 on Ubuntu Trusty is too old; we shall re-enable it once we figure out how to install an updated pyqt5 (>=5.5.1) without having to compile it from source...
=> travis: run tests on OS X instead of Linux

Lib/trufont/windows/fontInfoWindow.py
Otherwise we get locale-specific strings which can be invalid for UFO
format.
=> Use C locale for time/date string saved to UFO

Lib/trufont/__main__.py
Set the AA_UseHighDpiPixmaps so that Qt returns larger pixmaps for
Hi-DPI systems.
Before:
After:
=> Draw icons in Hi-DPI mode

Lib/trufont/__main__.py
Enables Hi-DPI scaling ion X11 without the need to set an environment
variable.
=> Set AA_EnableHighDpiScaling attribute to QApplication

Lib/trufont/windows/fontWindow.py
Otherwise loading a font from the recent files menu that was opened using
a relative path will fail when switching to a different directory.
=> Store absolute path of recent file

Lib/trufont/objects/defcon.py
Before, _set_sortDescriptor() checked if the new value was equal to the
old one and if so, returned early. This made it impossible to repeatedly
sort using the same descriptor, e.g. after having repeatedly added
glyphs without the sorting option in the "Add glyphs" dialog.
Fixes #430.
=> Make repeat sorting with the same sort descriptor possible.

Lib/trufont/windows/fontWindow.py
When adding glyphs and checking "Sort font" without having set a sort
descriptor in the "Sort" dialog first, an unhandled exception is thrown
by FontWindow._sortDescriptorChanged(). Return early on None.
Fixes bug #455.
The fix is not ideal (open sort dialog instead?), but better than an exception.
=> Handle sort_descriptor == None in FontWindow._sortDescriptorChanged()

Lib/trufont/objects/application.py
This reverts commit 0d6862ff29effc2e70df22223ef40c17a37c8f24.
The original bug can no longer be reproduced (see #333); additionally,
the workaround caused #423. Saving the last window with focus caused
random crashes on Linux when certain dialogs were closed, an issue with
object lifetimes may be involved.
=> Revert "application: fix menu switch"

Lib/trufont/objects/layoutEngine.py
Apparently feaLib will happily compile feature text using non-existent
glyphs, but compiling the table will obviously fail, so the compilation
step needs to be inside the try statement as well.
Without this change editing any glyphs in Reem Kufi source UFO will fail
as there are missing glyphs referenced by the feature code (they are
added at build time by the build script).
=> layoutEngine: Guard harder against feaLib failures

Lib/trufont/objects/defcon.py
After this commit 3df77f720b7f2bcfe01eaf4112b36b8bcb3f8462, I am seeing this error every time I try to import an OTF or TTF, which uses extractor.
The reason is we can't just assign `Font.newGlyph`, which is a class attribute, and thus an "unbound" method, to an instance as self.newGlyph.
In order to dynamically "bind" a method to an instance, we can use `types.MethodType`.
https://docs.python.org/3/library/types.html
Also, the original newGlyph method is restored with a try/finally block, in case anything goes wrong during the extraction.
=> Fix "TypeError: newGlyph() missing 1 required positional argument"

Lib/trufont/windows/fontWindow.py, requirements.txt, setup.py
This way one can copy glyphs from TruFont and paste them into Inkscape. We might want to support other vector formats for popular vector graphics editors.
=> Export SVG to the clipboard as well

Lib/trufont/objects/settings.py
Clearing the list would work, but upon constructing a new one, the type
of the empty list was set to "str" instead of "list", which resulted in
an exception when loading a new font tried to insert that font into the
recent files list.
Fixes bug #399.
=> Fix clearing recent files list

Lib/trufont/controls/glyphDialogs.py, Lib/trufont/drawingTools/selectionTool.py
Adjusting the exact position of an anchor is often needed, and without
this patch I find myself opening the glif files in a text editor to edit
the anchors.
=> Allow editing anchor coordinates on double click

requirements.txt
Fixes issue #537
TruFont won't run for me on Arch and Ubuntu unless ufoLib-2.1.1 is installed, changing ufoLib==2.1.0 to ufoLib==2.1.1 in requirements.txt fixes the problem.
=> Update ufoLib-2.1.0 to ufoLib-2.1.1

Lib/trufont/windows/fontWindow.py
If the glyph character (from the unicode value) is different than the
glyph name, show it in parenthesis as well.
Fixes https://github.com/trufont/trufont/issues/387.
=> Always show glyph name in the glyph tab title

Lib/trufont/controls/glyphCanvasView.py
Helpful for using glif files created from svg for example.
If the glyph has components, and they should pre-exist in UFO.
=> Support drag and dropping .glif files to glyph canvas

src/trufont/objects/factories.py
Fixes https://github.com/trufont/trufont/issues/598.
http://unifiedfontobject.org/versions/ufo3/glyphs/glif/#contour says a contour only containing off-curves must be treated as quadratic. Still need to implement that.
Also: more resilience to invalid curves like 3 off-curves and a `curve`? Ideally, this is caught and the UI displays the glyph as containing invalid contours, allowing the user to go in and fix it...
=> WX: Handle quadratic curves

requirements.txt
I know the main work is being done at wx branch. But to make the master branch usable, it is must to udpate the dependencies. 
Addresses #623 too.
This makes the master version usable by cloning the repo, `pip install -r requirements.txt` and then `pip install -e .`
=> Update requirements to use latest dependencies

.pre-commit-config.yaml, requirements.txt, setup.cfg
This finally gets rid of the old ufoLib dependency.
Closes #684.
Hopefully.
=> Depend on new ufo-extractor, update rest of deps

Lib/trufont/__main__.py, Lib/trufont/tools/platformSpecific.py, setup.cfg
Changes the application title from the default "Python" to "TruFont" for macOS.
It requires pyobjc-framework-Cocoa.
Fixes the macOS side of #555
=> Set application title on macOS

Lib/trufont/windows/fontWindow.py
I often edit multiple fonts by starting trufont from the command line with a wildcard file specification. There is no key shortcut for closing a font window; but individual tabs can be closed with ctrl/W, and ctrl/Q closes all windows. This pull request generalizes ctrl/W to close either a glyph tab or the main window. For repetitive actions, this greatly reduces required mouse actions for my use case (and with laptop mice being finicky creatures, this prevents the occasional mishap when I'm editing fonts on the road).
I cannot foresee any user confusion as a result of this change, but I'm no UX expert.
=> Hook up control/W on main window to close open font

Lib/trufont/windows/fontWindow.py
It took me forever to discover that the Find menu action was hooked up all the time, but silently ignored when not in the Glyph View. Disabling the Find menu item when not in Glyph View provides visual feedback that the menu isn't active in the main window, thus reducing frustration for new users. This may help a tiny bit with issue #138.
=> Disable find menu entry when not in Glyph View

Lib/defconQt/representationFactories/glyphCellFactory.py, Lib/defconQt/tools/platformSpecific.py
Bump GlyphCellHeaderHeight to 15 (from 13) for Linux. This fixes the clipping mentioned in issue #438, at least on my system (Ubuntu 20.04).
Reworked to use platform specific helper function, replacing PR 764. For optimum results, should be reworked to actually measure UI font height.
=> Bump GlyphCellHeaderHeight to 15 (from 13) for Linux.
