.travis.yml
Lib/defconQt/__main__.py
Lib/defconQt/baseCodeEditor.py
Lib/defconQt/featureTextEditor.py
Lib/defconQt/fontInfo.py
Lib/defconQt/fontView.py
Lib/defconQt/glyphCollectionView.py
Lib/defconQt/glyphView.py
Lib/defconQt/groupsView.py
Lib/defconQt/layerSetList.py
Lib/defconQt/objects/defcon.py
Lib/defconQt/pens/copySelectionPen.py
Lib/defconQt/representationFactories/__init__.py
Lib/defconQt/representationFactories/glyphViewFactory.py
Lib/defconQt/representationFactories/qPainterPathFactory.py
Lib/defconQt/scriptingWindow.py
Lib/defconQt/spaceCenter.py
setup.cfg
setup.py

Should the unused variables and unused import from 5cf4904 and 0fa018b just be removed?

PEP8 and lint code with flake8 on Travis CI

---

Lib/defconQt/layerSetList.py

Undo https://github.com/trufont/trufont/commit/ec2cda36e2e12301dbd96afcf21e30298f95c83e#diff-63b827e0c990e4937144d052e54e794cR6

layerSetList: Uncomment import icons_db

---

Lib/defconQt/fontView.py
Lib/defconQt/glyphCollectionView.py
Lib/defconQt/glyphView.py
Lib/defconQt/spaceCenter.py

spaceCenter: comboBox, bugfix

---

Lib/defconQt/fontView.py
Lib/defconQt/glyphCollectionView.py
Lib/defconQt/groupsView.py

Closes #28.
Closes #30.
Closes #41.

glyphCollectionView: fix scroll/ptSize/insert, fontView: sort tooltip

---

Lib/defconQt/fontInfo.py
tests/defconQt/fontInfo_test.py

- Merge patch from #16
- Refactor how tabs load and write info data
- Fix bug introduced with https://github.com/trufont/trufont/commit/63f83224f474c2c191e8cac3cb6bda8f2cb81b7d#diff-cae4a348ae503edbfb0602d0ec547d37R171
- Add unittest for most info data

fontInfo: Add OS/2 tab, add class TabWidget, use load and write functions

---

INSTALL.txt
Lib/defconQt/__main__.py
setup.py
trufont

Making it a little easier to install and use on Ubuntu/Debian...

Ubuntu/Debian installation steps + setup.py tweaks

---

INSTALL.txt

Partially addresses https://github.com/trufont/trufont/issues/53

INSTALL.txt: Add OS X instructions

---

Lib/defconQt/fontView.py

fontView: set Ctrl+G as shortcut for Add glyph, Ctrl+Alt+G is used for Groups window

---

INSTALL.md
MANIFEST.in

INSTALL.txt: Add OS X instructions
INSTALL.md: Minor fixes, including apt-get install qtsvg for GNU
rename INSTALL.txt -> INSTALL.md
correct tab to spaces
MANIFEST.in: Update INSTALL.{txt,md}
Conflicts:
INSTALL.txt

INSTALL.md changes submitted by Dave Crossland

---

Lib/defconQt/fontView.py

[fontView] s/Mark/Flag/g in UI strings only

---

Lib/defconQt/glyphView.py

glyphView: fix knife tool for multiple cuts on one segment

---

Lib/defconQt/fontView.py
Lib/defconQt/glyphView.py

fontView, glyphView: don't copy name

---

.travis.yml
requirements.txt

requirements.txt: use -e (editable) mode for packages cloned from git repository

---

Lib/defconQt/fontView.py
Lib/defconQt/representationFactories/glyphViewFactory.py
Lib/defconQt/tools/selectionTool.py

Closes #161.
Closes #162.
Closes #166.

meta: some fixups

---

.gitignore
Lib/defconQt/fontInfo.py
Lib/defconQt/fontView.py
Lib/defconQt/util/rlabel.py

A first sweep. Still needs a more pleasant resizing behavior.
Other dialogs will follow.

Font Info: Align labels right

---

Lib/defconQt/__main__.py
Lib/defconQt/baseCodeEditor.py
Lib/defconQt/featureTextEditor.py
Lib/defconQt/fontView.py
Lib/defconQt/glyphCollectionView.py
Lib/defconQt/glyphView.py
Lib/defconQt/metricsWindow.py
Lib/defconQt/objects/colorWidgets.py
Lib/defconQt/objects/defcon.py
Lib/defconQt/representationFactories/glyphViewFactory.py
Lib/defconQt/scriptingWindow.py
Lib/defconQt/tools/penTool.py
Lib/defconQt/tools/selectionTool.py
Lib/defconQt/util/drawing.py
requirements.txt
setup.py

cc #226.
Closes #230.
Closes #242.

meta: add an event dispatcher

---

.travis.yml

travis: run tests on both OS X and Ubuntu Trusty

---

Lib/trufont/representationFactories/glyphCellFactory.py

This is followup to https://github.com/adrientetar/defconQt/pull/5

Update to match defconQt Hi-DPI change

---

requirements.txt

requirements.txt: add --find-links to download booleanOperations==0.4 from Github Releases page

---

Lib/trufont/controls/glyphCanvasView.py

Support drag and dropping SVG images as glyphs

---

Lib/trufont/drawingTools/shapesTool.py
Lib/trufont/objects/application.py

Shapes tool

---

Lib/trufont/windows/fontFeaturesWindow.py

Fixes https://github.com/trufont/trufont/issues/385.

Save the font when saving the features as well

---

src/trufont/objects/application.py

Convert UFOs on the fly to tfont objects.

Support opening non-tfont files

---

Lib/trufont/windows/fontInfoWindow.py

left-pad minor version number with zeroes

---

Lib/trufont/windows/fontInfoWindow.py

fix bit values for OS2CodePageRanges

---

Lib/defconQt/controls/glyphContextView.py

Added pinch to zoom for macOS.
Closes #244

Enable pinch to zoom on macOS (Issue #244)

---

Lib/trufont/objects/application.py

Fixes #705
For your consideration. Review on commit level advised.

Fix open/import file dialog filter (fixes #705)

---

Lib/trufont/windows/metricsWindow.py

set index of combo box during initialization
